name: Train Model Pipeline

on:
  push:
    branches:
      - main  # Executa o pipeline ao fazer push na branch main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    # Etapa 1: Baixar o código do repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Etapa 2: Configurar o ambiente Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    # Etapa 3: Instalar dependências
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow keras

    # Etapa 4: Executar o código para treinar o modelo
    - name: Train the model
      run: |
        python train_model.py

    # Etapa 5: Salvar o modelo como um artifact
    - name: Upload trained model
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: cat_dog_classifier.h5
